name = "bitswap-restore"

[builders."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/avalonche/bitswap-restore"
exec_pkg = "."

# TODO: exec:go does not support traffic shaping, hence you should not use it
#  with this test plan.
[builders."exec:go"]
enabled = true
module_path = "github.com/avalonche/bitswap-restore"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "ipfs"
instances = { min = 2, max = 64, default = 2 }

  [testcases.params]
  timeout_secs = { type = "int", desc = "timeout", unit = "seconds", default = 300 }
  file_size = { type = "int", desc = "file size", unit = "bytes", default = 4194304 }
  unavailable_count = {type = "int", desc = "number of unavailable nodes that are down", unit = "peers", default = 0 }
  replication_factor = {type = "int", desc = "number of times the file is replicated", unit = "times", default = 0 }

[[testcases]]
name = "reed-solomon"
instances = { min = 2, max = 64, default = 2}

  [testcases.params]
  timeout_secs = { type = "int", desc = "timeout", unit = "seconds", default = 300 }
  file_size = { type = "int", desc = "file size", unit = "bytes", default = 4194304 }
  unavailable_count = {type = "int", desc = "number of unavailable nodes that are down", unit = "peers", default = 0 }
  parity = { type = "int", desc = "number of parity blocks", default = 3 }

[[testcases]]
name = "entanglement"
instances = { min = 2, max = 64, default = 2}

  [testcases.params]
  timeout_secs = { type = "int", desc = "timeout", unit = "seconds", default = 300 }
  file_size = { type = "int", desc = "file size", unit = "bytes", default = 4194304 }
  unavailable_count = {type = "int", desc = "number of unavailable nodes that are down", unit = "peers", default = 0 }
